package com.bike.controller;

import com.bike.common.Result;
import com.bike.entity.DispatchTask;
import com.bike.entity.HeatPoint;
import com.bike.service.DispatchService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

/**
 * 调度管理控制器
 * 
 * @author bike-sharing
 */
@Tag(name = "调度管理", description = "车辆调度、热力图、自动调度任务等接口")
@RestController
@RequestMapping("/api/dispatch")
@CrossOrigin
public class DispatchController {

    @Autowired
    private DispatchService dispatchService;

    @Operation(summary = "获取所有调度任务")
    @GetMapping("/tasks")
    public Result<List<DispatchTask>> getAllTasks() {
        return Result.success(dispatchService.getAllTasks());
    }

    @Operation(summary = "按优先级排序获取任务")
    @GetMapping("/tasks/sorted")
    public Result<List<DispatchTask>> getSortedTasksByPriority() {
        return Result.success(dispatchService.getSortedTasksByPriority());
    }

    @Operation(summary = "获取运维人员的任务")
    @GetMapping("/tasks/staff/{staffId}")
    public Result<List<DispatchTask>> getTasksByStaffId(
            @Parameter(description = "运维人员ID") @PathVariable Long staffId) {
        return Result.success(dispatchService.getTasksByStaffId(staffId));
    }

    @Operation(summary = "获取任务详情")
    @GetMapping("/tasks/{id}")
    public Result<DispatchTask> getTaskById(@Parameter(description = "任务ID") @PathVariable Long id) {
        return Result.success(dispatchService.getTaskById(id));
    }

    @Operation(summary = "创建调度任务")
    @PostMapping("/tasks")
    public Result<DispatchTask> createTask(@RequestBody DispatchTask task) {
        return Result.success(dispatchService.createDispatchTask(task));
    }

    @Operation(summary = "更新调度任务")
    @PutMapping("/tasks/{id}")
    public Result<DispatchTask> updateTask(
            @Parameter(description = "任务ID") @PathVariable Long id,
            @RequestBody DispatchTask task) {
        return Result.success(dispatchService.updateDispatchTask(id, task));
    }

    @Operation(summary = "接受任务")
    @PostMapping("/tasks/{id}/accept")
    public Result<DispatchTask> acceptTask(
            @Parameter(description = "任务ID") @PathVariable Long id,
            @Parameter(description = "运维人员ID") @RequestParam Long staffId,
            @Parameter(description = "运维人员姓名") @RequestParam String staffName) {
        return Result.success(dispatchService.acceptTask(id, staffId, staffName));
    }

    @Operation(summary = "完成任务")
    @PostMapping("/tasks/{id}/complete")
    public Result<DispatchTask> completeTask(@Parameter(description = "任务ID") @PathVariable Long id) {
        return Result.success(dispatchService.completeTask(id));
    }

    @Operation(summary = "删除任务")
    @DeleteMapping("/tasks/{id}")
    public Result<Void> deleteTask(@Parameter(description = "任务ID") @PathVariable Long id) {
        dispatchService.deleteTask(id);
        return Result.success();
    }

    @Operation(summary = "获取所有热力点")
    @GetMapping("/heatpoints")
    public Result<List<HeatPoint>> getAllHeatPoints() {
        return Result.success(dispatchService.getAllHeatPoints());
    }

    @Operation(summary = "按时间范围获取热力点")
    @GetMapping("/heatpoints/recent")
    public Result<List<HeatPoint>> getHeatPointsByTimeRange(
            @Parameter(description = "小时数") @RequestParam(defaultValue = "24") int hours) {
        return Result.success(dispatchService.getHeatPointsByTimeRange(hours));
    }

    @Operation(summary = "添加热力点")
    @PostMapping("/heatpoints")
    public Result<HeatPoint> addHeatPoint(@RequestBody HeatPoint heatPoint) {
        return Result.success(dispatchService.addHeatPoint(heatPoint));
    }

    @Operation(summary = "生成调度建议")
    @GetMapping("/suggestions")
    public Result<Map<String, Object>> generateDispatchSuggestions() {
        return Result.success(dispatchService.generateDispatchSuggestions());
    }

    @Operation(summary = "自动生成调度任务")
    @PostMapping("/auto-generate")
    public Result<DispatchTask> autoGenerateTask(
            @Parameter(description = "源区域ID") @RequestParam Long fromAreaId,
            @Parameter(description = "目标区域ID") @RequestParam Long toAreaId,
            @Parameter(description = "车辆数量") @RequestParam int bikeCount) {
        return Result.success(dispatchService.autoGenerateDispatchTask(fromAreaId, toAreaId, bikeCount));
    }
}
