bind 127.0.0.1
port 6379
timeout 0
tcp-keepalive 300
loglevel notice
logfile ""
databases 16
stop-writes-on-bgsave-error no
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir ./
appendonly no
